### ISSUE TITLE
adept-register and adept-download

### ISSUE THREAD

**Issue by hackerb9** [BentonEdmondson/libgourou-utils#2]
I couldn't run knock because it was missing two binaries and it was not clear what was needed to get them. 

It would be nice if this version of libgorou-utils created adept-register and adept-download directly instead of renaming them from adept_activate and acsmdownloader via the flake.nix file. (Not everyone is using flake.nix yet). 

Alternately, perhaps `knock` could try falling back to adept_activate and acsmdownloader if it can't find the new names.

**Comment by BentonEdmondson** [comment]
In the next release of knock, I will be moving from using this derivation of libgourou to the one defined [here](https://github.com/BentonEdmondson/benpkgs/tree/main/packages/libgourou) which is easier to update, and which doesn't change the binary names. This repo will then be archived or deleted.
