### ISSUE TITLE
utils/Makefile ought to default to looking in /usr/local/lib for libgourou.so

### ISSUE THREAD

**Issue by hackerb9** [BentonEdmondson/libgourou-utils#3]
/usr/local/lib is for locally installed libraries that are not prepackaged, such as libgourou on most systems. Currently the adept-register and adept-download commands do not check it at run time for the libgourou library. This is easily remedied by adding `export LD_RUN_PATH=/usr/local/lib` to the Makefile. 

```patch
diff --git a/utils/Makefile b/utils/Makefile
index cd15354..ea9c40a 100644
--- a/utils/Makefile
+++ b/utils/Makefile
@@ -1,10 +1,10 @@
-
 TARGETS=acsmdownloader adept_activate
 
 CXXFLAGS=-Wall `pkg-config --cflags Qt5Core Qt5Network` -fPIC -I$(ROOT)/include
 ifneq ($(STATIC_UTILS),)
 LDFLAGS=`pkg-config --libs Qt5Core Qt5Network` -L$(ROOT) $(ROOT)/libgourou.a -lcrypto -lzip
 else
+export LD_RUN_PATH=/usr/local/lib
 LDFLAGS=`pkg-config --libs Qt5Core Qt5Network` -L$(ROOT) -lgourou -lcrypto -lzip -lz -lpugixml
 endif
```

**Comment by BentonEdmondson** [comment]
This repo exists for the sole purpose of packaging libgourou with Nix with as few changes as possible. This is stated clearly in the readme. Nix doesn't have `/usr/local/lib`. If you are not using Nix, this repo is not applicable to you; you should be building the upstream package (http://indefero.soutade.fr/p/libgourou/).
